version: '3'

services:
  dev:    
    build:
      context: .
      dockerfile: appl.Dockerfile
    volumes:
    -   .:/root/projects
    - .:/root/.vscode-server
  mlflow:
    image: akraradets/ait-ml-mlflow:2023
    platform: linux/x86_64
    build: 
      context: .
      dockerfile: mlflow.Dockerfile
    ports:
      - 5000:5000